language: python

python:
    - 2.7
    - 3.2
    - 3.3
    - 3.4
before_install:
    - pip install cython
install: 
    - bash bootstrap
    - ./configure
    - make
    - sudo make install
    - python setup.py build_ext  --include-dirs=/usr/include/:/usr/local/include/colibri-core/ --library-dirs=/usr/lib:/usr/local/lib/ install
script: 
    - colibri-test
    - LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib/" python test.py
    
